"""
Django settings for academia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jjqp697qewod25#8r=sua%2x76^ab1-kgm(w7eoajp@rj7#x8d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    # Nuevas apps para la API REST
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← Nueva línea para CORS
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'academia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],  # ← CAMBIO AQUÍ
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'academia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mydb',              # nombre de la base de datos
        'USER': 'root',              # usuario de MySQL
        'PASSWORD': '1005538729',    # contraseña de MySQL
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'  # Español de Colombia

TIME_ZONE = 'America/Bogota'  # Zona horaria de Colombia

USE_I18N = True

USE_TZ = False  # False para compatibilidad con MySQL sin configuración adicional


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']

# Media files (uploads de usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===================================
# CONFIGURACIÓN DE EMAIL
# ===================================

# 🔧 MODO DESARROLLO (Recomendado para testing)
# Los emails se muestran en la terminal del servidor, no se envían realmente
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 🔧 MODO PRODUCCIÓN CON GMAIL (Descomentar cuando tengas las credenciales)
# Necesitas crear una "Contraseña de aplicación" en Google Account
# https://myaccount.google.com/apppasswords

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'wtarazona98@gmail.com'  # ← Cambia por tu email
# EMAIL_HOST_PASSWORD = 'xxxx xxxx xxxx xxxx'  # ← Contraseña de aplicación (16 caracteres)
# DEFAULT_FROM_EMAIL = 'Academia de Idiomas <wtarazona98@gmail.com>'
# SERVER_EMAIL = EMAIL_HOST_USER

# 🔧 MODO PRODUCCIÓN CON OUTLOOK/HOTMAIL (Alternativa)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp-mail.outlook.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu_correo@outlook.com'  # ← Cambia por tu email
# EMAIL_HOST_PASSWORD = 'tu_contraseña'  # ← Tu contraseña de Outlook
# DEFAULT_FROM_EMAIL = 'Academia de Idiomas <tu_correo@outlook.com>'
# SERVER_EMAIL = EMAIL_HOST_USER


# ===================================
# CONFIGURACIÓN DE SEGURIDAD
# ===================================

# Solo para producción (comentar en desarrollo)
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'


# ===================================
# CONFIGURACIÓN DE SESIONES
# ===================================

# Duración de la sesión (2 semanas)
SESSION_COOKIE_AGE = 1209600  # segundos

# La sesión expira al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Guardar la sesión en cada request
SESSION_SAVE_EVERY_REQUEST = False


# ===================================
# CONFIGURACIÓN DE LOGGING (Opcional)
# ===================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# ===================================
# CONFIGURACIÓN DE AUTENTICACIÓN
# ===================================

# URL de login y logout
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Backend de autenticación (por si quieres usar email en lugar de username)
# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
# ]


# ===================================
# CONFIGURACIÓN REGIONAL
# ===================================

# Formato de fecha
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i:s'
SHORT_DATE_FORMAT = 'd/m/Y'

# Formato de números
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','


# ===================================
# CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS (Producción)
# ===================================

# Para cuando uses 'python manage.py collectstatic'
# STATIC_ROOT = BASE_DIR / 'staticfiles'


# ===================================
# OTRAS CONFIGURACIONES ÚTILES
# ===================================

# Tamaño máximo de archivos subidos (5MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB en bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880

# Permitir iframes del mismo origen
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Configuración de mensajes de Django
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# ===================================
# CONFIGURACIÓN DE DJANGO REST FRAMEWORK
# ===================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}


# ===================================
# CONFIGURACIÓN DE JWT (JSON Web Tokens)
# ===================================

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


# ===================================
# CONFIGURACIÓN DE CORS
# ===================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Si uso React/Vue en el futuro
    "http://localhost:8000",  # Tu servidor Django
]

CORS_ALLOW_CREDENTIALS = True