# Generated by Django 5.2.7 on 2025-10-05 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Nivel_mcerl', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=2)),
                ('Modalidad', models.CharField(choices=[('sincrónica', 'Sincrónica'), ('asincrónica', 'Asincrónica')], max_length=12)),
                ('Estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=100, unique=True)),
                ('Contrasena', models.CharField(max_length=255)),
                ('Rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('admin', 'Administrador')], max_length=11)),
                ('Fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('idClase', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_hora', models.DateTimeField()),
                ('Enlace_clase', models.CharField(max_length=255)),
                ('Tipo', models.CharField(choices=[('sincrónica', 'Sincrónica'), ('asincrónica', 'Asincrónica')], max_length=12)),
                ('Material_asociado', models.CharField(max_length=255)),
                ('idCurso', models.ForeignKey(db_column='idCurso', on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='core.curso')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'Clase',
                'ordering': ['Fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Fecha', models.DateField()),
                ('idCurso', models.ForeignKey(db_column='idCurso', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='core.curso')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'Evaluacion',
                'ordering': ['Fecha'],
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('pendiente', 'Pendiente')], default='abierto', max_length=10)),
                ('Asunto', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'db_table': 'TicketSoporte',
                'ordering': ['-Fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvaluacion',
            fields=[
                ('idResultado', models.AutoField(primary_key=True, serialize=False)),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Retroalimentacion', models.TextField()),
                ('idEvaluacion', models.ForeignKey(db_column='idEvaluacion', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.evaluacion')),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Resultado de Evaluación',
                'verbose_name_plural': 'Resultados de Evaluaciones',
                'db_table': 'ResultadoEvaluacion',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('Asistencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Progreso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Comentarios_profesor', models.TextField()),
                ('idCurso', models.ForeignKey(db_column='idCurso', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.curso')),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('idRecibo', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=10)),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
                'db_table': 'ReciboPago',
                'ordering': ['-Fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('Contenido', models.TextField()),
                ('Fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('Destinatario', models.ForeignKey(db_column='Destinatario', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='core.usuario')),
                ('Remitente', models.ForeignKey(db_column='Remitente', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensaje',
                'ordering': ['-Fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('idLog', models.AutoField(primary_key=True, serialize=False)),
                ('Accion', models.CharField(max_length=100)),
                ('Fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('Detalle', models.TextField()),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'db_table': 'LogActividad',
                'ordering': ['-Fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='IdiomaInterfaz',
            fields=[
                ('idIdioma', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_idioma', models.CharField(max_length=2)),
                ('Nombre', models.CharField(max_length=50)),
                ('Por_defecto', models.BooleanField(default=False)),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='idiomas_preferidos', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Idioma de Interfaz',
                'verbose_name_plural': 'Idiomas de Interfaz',
                'db_table': 'IdiomaInterfaz',
            },
        ),
        migrations.CreateModel(
            name='ContenidoEducativo',
            fields=[
                ('idContenido', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Tipo', models.CharField(choices=[('PDF', 'PDF'), ('video', 'Video'), ('audio', 'Audio'), ('enlace', 'Enlace')], max_length=6)),
                ('Archivo_url', models.CharField(max_length=255)),
                ('idCurso', models.ForeignKey(db_column='idCurso', on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.curso')),
                ('Subido_por', models.ForeignKey(db_column='Subido_por', on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_subidos', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Contenido Educativo',
                'verbose_name_plural': 'Contenidos Educativos',
                'db_table': 'ContenidoEducativo',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_inscripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='activa', max_length=10)),
                ('idCurso', models.ForeignKey(db_column='idCurso', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.curso')),
                ('idUsuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'Inscripcion',
                'unique_together': {('idUsuario', 'idCurso')},
            },
        ),
    ]
