# Generated by Django 5.2.7 on 2025-10-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsoporte',
            name='email_usuario',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='idUsuario',
            field=models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.usuario'),
        ),
    ]
