# Generated by Django 5.2.7 on 2025-10-13 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_contrasena_usuario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('idCurso', models.ForeignKey(db_column='idCurso', on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='core.curso')),
                ('idProfesor', models.ForeignKey(db_column='idProfesor', limit_choices_to={'Rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_enseña', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Profesor-Curso',
                'verbose_name_plural': 'Profesores-Cursos',
                'db_table': 'ProfesorCurso',
                'unique_together': {('idProfesor', 'idCurso')},
            },
        ),
    ]
